#!/bin/bash
# Managed branded MOTD (idempotent). Regenerated by the VPS bot.
# Do not edit manually — changes will be overwritten on reinstall.
reset=$'\033[0m'
bold=$'\033[1m'
p_color=$'\033[{PRIMARY_COLOR}m'
s_color=$'\033[{SECONDARY_COLOR}m'
p_line="━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

cpu_usage() {
    read -r _ u1 n1 s1 i1 _ < /proc/stat
    t1=$((u1 + n1 + s1 + i1))
    busy1=$((u1 + n1 + s1))
    sleep 0.4 2>/dev/null || sleep 1
    read -r _ u2 n2 s2 i2 _ < /proc/stat
    t2=$((u2 + n2 + s2 + i2))
    busy2=$((u2 + n2 + s2))
    dt=$((t2 - t1))
    db=$((busy2 - busy1))
    if [ "$dt" -gt 0 ]; then
        echo $((100 * db / dt))
    else
        echo 0
    fi
}

{LOGO_BLOCK}

{MOTD_BODY}
